version: "3"

services:
  chatto:
    image: jaimeteb/chatto:v0.4.0
    env_file: .env
    ports:
      - "4774:4770"
    volumes:
      - ./data:/chatto/data
    depends_on:
      - ext
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  ext:
    build:
      dockerfile: data/ext/Dockerfile
      context: .
    expose:
      - 8774
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
