service: chatto-trivia-pro-extensions

provider:
  name: google
  stage: dev
  runtime: python37
  project: jaimeteb
  credentials: ../.serverless-deployer.json

frameworkVersion: '3'

configValidationMode: off

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-scripts
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  rest:
    handler: entrypoint
    events:
      - http: path

# custom:
#   scripts:
#     commands:
#       make-public: |
#         gcloud functions add-iam-policy-binding ${self:service}-${self:provider.stage}-${opt:function, ''} \
#           --member="allUsers" \
#           --role="roles/cloudfunctions.invoker" \
#           --project=${self:provider.project}
#     hooks:
#       'after:deploy:deploy': |
#         npx sls make-public --function rest
