service: chatto-trivia-pro-chatto

provider:
  name: google
  stage: dev
  runtime: go119
  project: jaimeteb
  credentials: ../.serverless-deployer.json
  environment: ${file(../.env.json)}

frameworkVersion: '3'

configValidationMode: off

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-scripts  

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  telegram:
    handler: TelegramHandler
    events:
      - http: path
  rest:
    handler: RESTHandler
    events:
      - http: path

# custom:
#   scripts:
#     commands:
#       make-public: |
#         gcloud functions add-iam-policy-binding ${self:service}-${self:provider.stage}-${opt:function, ''} \
#           --member="allUsers" \
#           --role="roles/cloudfunctions.invoker" \
#           --project=${self:provider.project}
#     hooks:
#       'after:deploy:deploy': |
#         npx sls make-public --function telegram
#         npx sls make-public --function rest
