name: serverless-deploy

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  serverless-deploy:
    name: serverless deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Load credentials
      run: |
        mkdir ~/.gcloud
        echo '${{ secrets.GCLOUD_SERVERLESS_DEPLOYER }}' > ~/.gcloud/serverless-deployer.json
        echo '${{ secrets.CHATTO_TRIVIA_PRO_ENV }}' > .env.json
        ls -l ~/.gcloud/serverless-deployer.json
        ls -l .env.json
    # chatto
    - run: cd ./chatto && npm ci
    - name: serverless deploy chatto
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./chatto && serverless deploy"
        entrypoint: /bin/sh
    # extensions
    - run: cd ./extensions && npm ci
    - name: serverless deploy extensions
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./extensions && serverless deploy"
        entrypoint: /bin/sh
      
  